### ISSUE TITLE
too much traffic is wasted when playing video on web

### ISSUE THREAD

**Issue by ChengChung** [lordfriend/Deneb#165]
Sometimes I notice some lags when playing videos, thus I try to monitor the traffic to find out some reasons.
I find that http 206 requests happens too often, and sometimes twice or more in one second, the traffic graph also shows that the traffic-in keeps in 4-10MB/s almost all the time, and it means I finnaly download about 12GB contents to view a 300MB video. 
But the traffic staticstics on Chrome is normal and doesn't display any problems.
The latency between server and client is 40-50ms
I hope these information help.

**Comment by lordfriend** [comment]
Thank you for the information. I will investigate this abnormal behavior.

**Comment by lordfriend** [comment]
After some observation and search. I think it's the video file cause this issue. and somehow it's also a Chrome related issue. the videos are from third-party sources, so they may use some incorrect settings in encoding the mp4. That's why some videos don't have this issue.

the only solution is re-encoding the video which has an incorrect format.

**Comment by lordfriend** [comment]
This project is succeed by https://github.com/irohalab/mira-ui, and will be archived.
